# Generated by Django 4.2.5 on 2024-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
